### ISSUE TITLE
Cannot publish WASI command-line tool.

### ISSUE THREAD

**Issue by vi** [wasmerio/cargo-wapm#2]
There is a tool that can be built for WASI along with other non-wasm platforms.

But `cargo wapm` does not to publish it.

```
$ cargo wapm --dry-run
2022-08-12T21:39:43.681554Z  INFO publish: cargo_wapm: Publishing dry_run=true pkg="random-distributions-cli"
Error: Unable to publish "random-distributions-cli"

Caused by:
    The package doesn't contain a library with the "cdylib" crate-type
```

Or is WAPM only for libraries, not for executables, unlike `crates.io`?

**Comment by Michael-F-Bryan** [comment]
I believe this was fixed in 34613bd059c27e4f0290240f5a6c7567889248b2 (`v0.1.4`).
